# Generated by Django 4.2.5 on 2023-09-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='host',
        ),
    ]
